import React from 'react';
import { Link } from 'react-router-dom';

import Table from './Table';
import Sprite from './Sprite';
import MaxScroll from './MaxScroll';

const shops = [
    {
        name: 'Dagger',
        tile: 180,
        cost: 300,
        towns: ['Aria', "S'thel", 'Dondheim', 'Gombard', 'Nordolk'],
    },
    {
        name: 'Sword',
        tile: 86,
        cost: 300,
        towns: ['Aria', 'Gombard', 'Nordolk'],
    },
    {
        name: 'Cloak',
        tile: 129,
        cost: 50,
        towns: ['Aria', "S'thel", 'Dondheim'],
    },
    {
        name: 'Bow',
        tile: 90,
        cost: 300,
        towns: ['Aria', 'Gombard', 'Nordolk'],
    },
    {
        name: 'Boots',
        tile: 202,
        cost: 1000,
        towns: ['Aria', "S'thel", 'Dondheim', 'Gombard', 'Nordolk'],
    },
    {
        name: 'Robes',
        tile: 115,
        cost: 600,
        towns: ['Aria', 'Gombard', 'Nordolk'],
    },
    {
        name: 'Staff',
        tile: 94,
        cost: 300,
        towns: ['Aria', "S'thel", 'Dondheim', 'Gombard', 'Nordolk'],
    },
    {
        name: 'Bone Staff',
        tile: 231,
        cost: 800,
        towns: ['Aria', 'Durnik'],
    },
    {
        name: 'Long Bow',
        tile: 224,
        cost: 600,
        towns: [
            'Aria',
            "S'thel",
            'Dondheim',
            'Gombard',
            'Nordolk',
            'Toronega',
            'Thule',
            'Naleg',
            'Tal Mita',
            'Kor',
            'Ynys',
            'Tal Nivek',
            'Airlon',
            'Thicket',
        ],
    },
    {
        name: 'Ridged Dagger',
        tile: 226,
        cost: 350,
        towns: ['Aria', "S'thel", 'Dondheim', 'Gombard'],
    },
    {
        name: 'Wooden Shield',
        tile: 183,
        cost: 400,
        towns: ['Aria', "S'thel", 'Dondheim', 'Gombard', 'Nordolk', 'Toronega'],
    },
    {
        name: 'Leather Armor',
        tile: 165,
        cost: 500,
        towns: ['Aria', 'Dondheim', 'Gombard', 'Nordolk', 'Toronega'],
    },
    {
        name: 'Longsword',
        tile: 87,
        cost: 800,
        towns: [
            'Aria',
            "S'thel",
            'Dondheim',
            'Gombard',
            'Nordolk',
            'Toronega',
            'Paititi',
            'Thule',
            'Cennyn',
            'Naleg',
            'Tal Mita',
            'Kor',
            'Ynys',
            'Tal Nivek',
            'Airlon',
            'Thicket',
        ],
    },
    {
        name: 'Chainmail',
        tile: 169,
        cost: 7000,
        towns: [
            'Aria',
            "S'thel",
            'Dondheim',
            'Gombard',
            'Nordolk',
            'Toronega',
            'Paititi',
            'Thule',
            'Cennyn',
            'Naleg',
            'Tal Mita',
            'Kor',
            'Ynys',
            'Tal Nivek',
            'Airlon',
            'Thicket',
        ],
    },
    {
        name: 'Scalemail',
        tile: 167,
        cost: 12800,
        towns: [
            'Aria',
            "S'thel",
            'Dondheim',
            'Gombard',
            'Nordolk',
            'Toronega',
            'Paititi',
            'Thule',
            'Cennyn',
            'Naleg',
            'Tal Mita',
            'Kor',
            'Ynys',
            'Tal Nivek',
            'Airlon',
            'Thicket',
        ],
    },
    {
        name: 'Composite Bow',
        tile: 91,
        cost: 4850,
        towns: [
            'Aria',
            "S'thel",
            'Dondheim',
            'Gombard',
            'Nordolk',
            'Toronega',
            'Paititi',
            'Thule',
            'Cennyn',
            'Naleg',
            'Tal Mita',
            'Kor',
            'Ynys',
            'Tal Nivek',
            'Airlon',
        ],
    },
    {
        name: 'Shimmering Shield',
        tile: 186,
        cost: 11000,
        towns: ['Aria', 'Gombard', 'Nordolk'],
    },
    {
        name: 'Fire Arrow',
        tile: 110,
        cost: 30,
        towns: ['Aria', "S'thel", 'Gombard'],
    },
    {
        name: 'Pelt Cloak',
        tile: 131,
        cost: 1500,
        requirement: 'Pelting Them',
        towns: ['Aria'],
    },
    {
        name: 'Sandals of Hoff',
        tile: 370,
        cost: 3000,
        requirement: 'Behold!',
        towns: ['Aria'],
    },
    {
        name: 'Curved Sword',
        tile: 360,
        cost: 87500,
        requirement: 'Nasty Sting',
        towns: ['Aria'],
    },
    {
        name: 'Conical Helmet',
        tile: 339,
        cost: 11000,
        requirement: 'Making a Stand',
        towns: ['Aria'],
    },
    {
        name: 'Chaos Spear',
        tile: 379,
        cost: 111500,
        requirement: 'Portrait of Purity',
        towns: ['Aria'],
    },
    {
        name: 'Knee High Boots',
        tile: 51,
        cost: 2000,
        towns: ["S'thel"],
    },
    {
        name: 'Steel Shield',
        tile: 185,
        cost: 1000,
        towns: ["S'thel"],
    },
    {
        name: 'Kite Shield',
        tile: 6,
        cost: 26000,
        towns: ["S'thel"],
    },
    {
        name: 'Head Dress',
        tile: 371,
        cost: 3400,
        requirement: 'The Evil Beneath',
        towns: ["S'thel"],
    },
    {
        name: 'Diamond Knife',
        tile: 363,
        cost: 47800,
        requirement: 'Smashing Ice Cubes',
        towns: ["S'thel"],
    },
    {
        name: 'Troll Club',
        tile: 348,
        cost: 97500,
        requirement: 'Slithering Evil',
        towns: ["S'thel"],
    },
    {
        name: 'Prong Tome',
        tile: 369,
        cost: 32000,
        requirement: 'Dragons Egg Delivery',
        towns: ["S'thel"],
    },
    {
        name: 'Tiger Cloak',
        tile: 336,
        cost: 73500,
        requirement: 'Light the Way',
        towns: ["S'thel"],
    },
    {
        name: 'Spiked Shield',
        tile: 53,
        cost: 36000,
        towns: ['Dondheim'],
    },
    {
        name: 'Mighty Axe',
        tile: 204,
        cost: 800,
        towns: ['Dondheim'],
    },
    {
        name: 'Iron Helm',
        tile: 193,
        cost: 7000,
        towns: ['Dondheim'],
    },
    {
        name: 'Canabe Cloak',
        tile: 128,
        cost: 23500,
        towns: ['Dondheim'],
    },
    {
        name: 'Templar Armor',
        tile: 166,
        cost: 13500,
        towns: ['Dondheim'],
    },
    {
        name: 'Frost Arrow',
        tile: 111,
        cost: 50,
        towns: ['Dondheim', 'Nordolk'],
    },
    {
        name: 'Stinger Sword',
        tile: 206,
        cost: 11500,
        requirement: 'It Stings!',
        towns: ['Dondheim'],
    },
    {
        name: 'Cowled Robes',
        tile: 357,
        cost: 53500,
        requirement: 'Snakes Alive',
        towns: ['Dondheim'],
    },
    {
        name: 'Flinger',
        tile: 377,
        cost: 22600,
        requirement: 'Ghoul Hunt',
        towns: ['Dondheim'],
    },
    {
        name: 'Swamp Gloves',
        tile: 375,
        cost: 14500,
        requirement: 'Seedy Business',
        towns: ['Dondheim'],
    },
    {
        name: 'Red Stone Sceptre',
        tile: 378,
        cost: 92000,
        requirement: 'Medcinial Hope',
        towns: ['Dondheim'],
    },
    {
        name: 'Goif Gloves',
        tile: 146,
        cost: 13500,
        requirement: 'Lost Child',
        towns: ['Gombard'],
    },
    {
        name: 'Hunter Knife',
        tile: 227,
        cost: 10800,
        towns: ['Durnik', 'Nordolk', 'Toronega', 'Thule', 'Cennyn', 'Naleg', 'Tal Mita', 'Kor', 'Ynys', 'Tal Nivek', 'Airlon', 'Thicket'],
    },

    {
        name: 'Sickle',
        tile: 229,
        cost: 47800,
        towns: ['Durnik'],
    },
    {
        name: 'Dark Staff',
        tile: 233,
        cost: 46800,
        towns: ['Durnik'],
    },
    {
        name: 'Ring of Health',
        tile: 159,
        cost: 18500,
        towns: ['Hermit'],
    },
    {
        name: 'Task Spear',
        tile: 203,
        cost: 31500,
        towns: ['Hermit'],
    },
    {
        name: 'Shimmering Helm',
        tile: 23,
        cost: 21000,
        towns: ['Hermit'],
    },
    {
        name: 'Infused Robes',
        tile: 113,
        cost: 33500,
        towns: ['Hermit'],
    },

    {
        name: 'Lined Boots',
        tile: 354,
        cost: 8000,
        requirement: 'The Mighty Horn',
        towns: ['Nordolk'],
    },
    {
        name: 'Magicians Tunic',
        tile: 287,
        cost: 83500,
        requirement: 'Cull the Magic',
        towns: ['Nordolk'],
    },
    {
        name: 'Book of Majesty',
        tile: 321,
        cost: 65000,
        requirement: 'Blood of the Elders',
        towns: ['Nordolk'],
    },
    {
        name: 'Shadow Boots',
        tile: 338,
        cost: 48000,
        requirement: 'Newt Replacement',
        towns: ['Nordolk'],
    },
    {
        name: 'Spiked Club',
        tile: 364,
        cost: 19800,
        requirement: 'Chaos Mages Unite',
        towns: ['Nordolk'],
    },
    {
        name: 'Explosion Arrow',
        tile: 10,
        cost: 75,
        towns: ['Toronega', 'Paititi', 'Thule', 'Cennyn', 'Naleg', 'Tal Mita', 'Kor', 'Ynys', 'Tal Nivek', 'Airlon', 'Thicket'],
    },
    {
        name: 'Lined Cap',
        tile: 355,
        cost: 7000,
        requirement: '3 wishes',
        towns: ['Toronega'],
    },
    {
        name: 'Mustard Tome',
        tile: 353,
        cost: 45000,
        requirement: 'Creepers Peepers',
        towns: ['Toronega'],
    },
    {
        name: 'Juganaught Plate',
        tile: 358,
        cost: 67500,
        requirement: 'Jar of Wisps',
        towns: ['Toronega'],
    },
    {
        name: 'Clawed Gloves',
        tile: 343,
        cost: 63500,
        requirement: 'The Labyrinth',
        towns: ['Toronega'],
    },
    {
        name: 'Lava Rod',
        tile: 319,
        cost: 5000,
        requirement: 'Dragon Bashing',
        towns: ['Toronega'],
    },
    {
        name: 'Harp Bow',
        tile: 272,
        cost: 83600,
        towns: ['Jungle', 'Paititi'],
    },
    {
        name: 'Lion Blade',
        tile: 13,
        cost: 87500,
        towns: ['Paititi', 'Naleg', 'Tal Mita', 'Kor', 'Ynys', 'Tal Nivek', 'Airlon'],
    },
    {
        name: 'Lightning Shield',
        tile: 266,
        cost: 72000,
        towns: ['Thule', 'Cennyn'],
    },
];
export default function GearsShops() {
    return (
        <Table
            header={['Icon', 'Name', 'Price', 'Location', 'Requirement']}
            rows={shops.reduce((acc, item) => {
                return [
                    ...acc,
                    {
                        id: item.name.split(' ').join('_'),
                        data: [
                            <Sprite tile={item.tile} spriteSheet='tiles' className='sprite' title={item.name} alt={item.name} />,
                            <Link to={`/items#${item.name.split(' ').join('_')}`}>{item.name}</Link>,
                            item.cost,
                            <MaxScroll>
                                <ul>
                                    {item.towns.map((town, id) => (
                                        <li key={id}>{town}</li>
                                    ))}
                                </ul>
                            </MaxScroll>,
                            item.requirement ? (
                                <>
                                    Complete <Link to={`/quests#${item.requirement.split(' ').join('_')}`}>{item.requirement}</Link>
                                </>
                            ) : (
                                '–'
                            ),
                        ],
                    },
                ];
            }, [])}
        />
    );
}
